services:
  web:
    restart: always
    build: .
    container_name: go-mysql-crud
    ports:
      - "8006:8005"
    environment:
      - DB_USER=root
      - DB_PASS=12345
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=go-mysql-crud
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=go-mysql-crud
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge